django_test/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^home/(?P<username>.+)/$', views.home, name='home'),
    url(r'^article/$', views.article, name='article'),
    url(r'^about/$', views.about, name='about'),
    url(r'^timeline/$', views.timeline, name='timeline'),
    url(r'^resource/$', views.resource, name='resource'),
    # url(r'^detail/(?<pk>[0-9]+)/$', views.detail, name='detail'),

]

django_test/django_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app1.views import home, test1, test2, test3, Test1, Test2, Test3, Test4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/', include('blog.urls'), name='blog'),
]

django_test/app1/models.py
from django.db import models

# Create your models here.

class Test(models.Model):
    name = models.CharField(max_length=100)

class User(models.Model):
    # verbose_name = 'user'
    account = models.CharField(max_length=10)
    password = models.CharField(max_length=10)

    def __str__(self):
        return f'id:{self.id},account:{self.account},passwd:{self.password}'

django_test/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    about = models.CharField(max_length=200, default='无简介')
    text = models.TextField()
    created_time = models.DateTimeField(auto_now=True)
    change_time = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=20, default='root')
    views = models.IntegerField(default=0)

    class Meta:
        db_table = 'Post'

class User(models.Model):
    name = models.CharField(max_length=20)
    about = models.CharField(max_length=200)
    address = models.CharField(max_length=20)

django_test/app1/forms.py
from django import forms
from app1.models import User

# class LoginForm(forms.Form):
#     name = forms.CharField(max_length=20)
#     password = forms.CharField(max_length=1, widget=forms.PasswordInput(attrs={'class':'passwd'}))


class LoginForm(forms.ModelForm):
    # 元信息
    class Meta:
        model = User
        fields = '__all__'

django_test/app1/views.py
import time
from app1.models import Test, User
from app1.forms import LoginForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView, CreateView


# Create your views here.
def home(request):
    return redirect('https://www.baidu.com')


def test1(request):
    return HttpResponse('hello world')


def test2(request):
    now = time.ctime()
    login_form = LoginForm()
    method = request.method
    if method == 'GET':
        return render(request, 'test/test.html', {'time':now, 'form':login_form})
    else:
        # name = request.POST['name']
        # password = request.POST['password']
        params = request.POST.dict()
        form = LoginForm(params)
        if form.is_valid():
            data = form.cleaned_data
            return HttpResponse('登录成功')
        return HttpResponse('请重新输入')


def test3(request, num):
    id = num
    data = User.objects.filter(id=id)
    return render(request, 'test/Test2.html', {'data': data})


# 类视图
class Test1(TemplateView):
    template_name = 'test/Test1.html'


class Test2(ListView):
    model = User
    template_name = 'test/Test2.html'
    context_object_name = 'data'


class Test3(DetailView):
    model = User
    template_name = 'test/Test3.html'
    context_object_name = 'data'


class Test4(CreateView):
    model = User
    template_name = 'test/Test4.html'
    context_object_name = 'form'
    fields = '__all__'
    success_url = 'http://127.0.0.1:8000/Test4/?'

django_test/blog/views.py
from django.shortcuts import render
from .models import Post, User

# Create your views here.
def home(request, username):
    post_list = Post.objects.all()
    hot_post_list = Post.objects.all().order_by('-views')
    user = User.objects.filter(name=username).first()
    data = {
        'post_list': post_list,
        'hot_post_list': hot_post_list,
        'user': user
    }
    if request.method == 'GET':
        return render(request, 'blog/home.html', data)

def article(request):
    if request.method == 'GET':
        return render(request, 'blog/article.html')


def about(request):
    if request.method == 'GET':
        return render(request, 'blog/about.html')

def timeline(request):
    if request.method == 'GET':
        return render(request, 'blog/timeline.html')

def resource(request):
    if request.method == 'GET':
        return render(request, 'blog/resource.html')

def detail(request, pk):
    if request.method == 'GET':
        return render(request, 'blog/detail.html')

django_test/templates/blog/home.html
<!--
    
 @Name：不落阁整站模板源码
 @Author：Absolutely
 @Site：http://www.lyblogs.cn

 -->
{% load staticfiles %}
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; Charset=gb2312">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>不落阁 - 一个.NET程序员的个人博客网站</title>
    <link rel="shortcut icon" href={% static 'images/Logo_40.png' %} type="image/x-icon">
    <!--Layui-->
    <link href={% static 'plug/layui/css/layui.css' %} rel="stylesheet" />
    <!--font-awesome-->
    <link href={% static 'plug/font-awesome/css/font-awesome.min.css' %} rel="stylesheet" />
    <!--全局样式表-->
    <link href={% static 'css/global.css' %} rel="stylesheet" />
    <!-- 本页样式表 -->
    <link href={% static 'css/home.css'%} rel="stylesheet" />
</head>
<body>
    <!-- 导航 -->
    <nav class="blog-nav layui-header">
        <div class="blog-container">
            <!-- QQ互联登陆 -->
            <a href="javascript:;" class="blog-user">
                <i class="fa fa-qq"></i>
            </a>
            <a href="javascript:;" class="blog-user layui-hide">
                <img src={% static 'images/Absolutely.jpg' %} alt="Absolutely" title="Absolutely" />
            </a>
            <!-- 不落阁 -->
            <a class="blog-logo" href="home.html">不落阁</a>
            <!-- 导航菜单 -->
            <ul class="layui-nav" lay-filter="nav">
                <li class="layui-nav-item layui-this">
                    <a href="home.html"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'blog:article' %}"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
                </li>
                <li class="layui-nav-item">
                    <a href={% url 'blog:resource' %}><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
                </li>
                <li class="layui-nav-item">
                    <a href={% url 'blog:timeline' %}><i class="fa fa-hourglass-half fa-fw"></i>&nbsp;点点滴滴</a>
                </li>
                <li class="layui-nav-item">
                    <a href={% url 'blog:about' %}><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
                </li>
            </ul>
            <!-- 手机和平板的导航开关 -->
            <a class="blog-navicon" href="javascript:;">
                <i class="fa fa-navicon"></i>
            </a>
        </div>
    </nav>
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <!-- canvas -->
        <canvas id="canvas-banner" style="background: #393D49;"></canvas>
        <!--为了及时效果需要立即设置canvas宽高，否则就在home.js中设置-->
        <script type="text/javascript">
            var canvas = document.getElementById('canvas-banner');
            canvas.width = window.document.body.clientWidth - 10;//减去滚动条的宽度
            if (screen.width >= 992) {
                canvas.height = window.innerHeight * 1 / 3;
            } else {
                canvas.height = window.innerHeight * 2 / 7;
            }
        </script>
        <!-- 这个一般才是真正的主体内容 -->
        <div class="blog-container">
            <div class="blog-main">
                <!-- 网站公告提示 -->
                <div class="home-tips shadow">
                    <i style="float:left;line-height:17px;" class="fa fa-volume-up"></i>
                    <div class="home-tips-container">
                        <span style="color: #009688">偷偷告诉大家，本博客的后台管理也正在制作，为大家准备了游客专用账号！</span>
                        <span style="color: red">网站新增留言回复啦！使用QQ登陆即可回复，人人都可以回复！</span>
                        <span style="color: red">如果你觉得网站做得还不错，来Fly社区点个赞吧！<a href="http://fly.layui.com/case/2017/" target="_blank" style="color:#01AAED">点我前往</a></span>
                        <span style="color: #009688">不落阁 &nbsp;—— &nbsp;一个.NET程序员的个人博客，新版网站采用Layui为前端框架，目前正在建设中！</span>
                    </div>
                </div>
                <!--左边文章列表-->
                <div class="blog-main-left">
                    {% for post in post_list %}
                        <div class="article shadow">
                            <div class="article-left">
                                <img src={% static 'images/cover/201703181909057125.jpg' %} alt="{{ post.title }}" />
                            </div>
                        <div class="article-right">
                            <div class="article-title">
                                <a href="detail.html">{{ post.title }}</a>
                            </div>
                            <div class="article-abstract">
                                {{ post.about }}
                            </div>
                        </div>
                        <div class="clear"></div>
                        <div class="article-footer">
                            <span><i class="fa fa-clock-o"></i>&nbsp;&nbsp;{{ post.created_time }}</span>
                            <span class="article-author"><i class="fa fa-user"></i>&nbsp;&nbsp;{{ post.author }}y</span>
                            <span><i class="fa fa-tag"></i>&nbsp;&nbsp;<a href="#">Web前端</a></span>
                            <span class="article-viewinfo"><i class="fa fa-eye"></i>&nbsp;{{ post.views }}</span>
                            <span class="article-viewinfo"><i class="fa fa-commenting"></i>&nbsp;4</span>
                        </div>
                    </div>
                    {% empty %}
                        暂无文章！
                    {% endfor %}
                </div>
                <!--右边小栏目-->
                <div class="blog-main-right">
                    <div class="blogerinfo shadow">
                        <div class="blogerinfo-figure">
                            <img src={% static 'images/Absolutely.jpg' %} alt="Absolutely" />
                        </div>
                        <p class="blogerinfo-nickname">{{ user.name }}</p>
                        <p class="blogerinfo-introduce">{{ user.about }}</p>
                        <p class="blogerinfo-location"><i class="fa fa-location-arrow"></i>&nbsp;{{ user.address }}</p>
                        <hr />
                        <div class="blogerinfo-contact">
                            <a target="_blank" title="QQ交流" href="javascript:layer.msg('启动QQ会话窗口')"><i class="fa fa-qq fa-2x"></i></a>
                            <a target="_blank" title="给我写信" href="javascript:layer.msg('启动邮我窗口')"><i class="fa fa-envelope fa-2x"></i></a>
                            <a target="_blank" title="新浪微博" href="javascript:layer.msg('转到你的微博主页')"><i class="fa fa-weibo fa-2x"></i></a>
                            <a target="_blank" title="码云" href="javascript:layer.msg('转到你的github主页')"><i class="fa fa-git fa-2x"></i></a>
                        </div>
                    </div>
                    <div></div><!--占位-->
                    <div class="blog-module shadow">
                        <div class="blog-module-title">热文排行</div>
                        <ul class="fa-ul blog-module-ul">
                            {% for  hot_post in hot_post_list%}
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="detail.html">{{ hot_post.title }}</a></li>
                            {% empty %}
                                暂无文章！
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">最近分享</div>
                        <ul class="fa-ul blog-module-ul">
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="http://pan.baidu.com/s/1c1BJ6Qc" target="_blank">Canvas</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="http://pan.baidu.com/s/1kVK8UhT" target="_blank">pagesize.js</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="https://pan.baidu.com/s/1mit2aiW" target="_blank">时光轴</a></li>
                            <li><i class="fa-li fa fa-hand-o-right"></i><a href="https://pan.baidu.com/s/1nuAKF81" target="_blank">图片轮播</a></li>
                        </ul>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">一路走来</div>
                        <dl class="footprint">
                            <dt>2017年03月12日</dt>
                            <dd>新增留言回复功能！人人都可参与回复！</dd>
                            <dt>2017年03月10日</dt>
                            <dd>不落阁2.0基本功能完成，正式上线！</dd>
                            <dt>2017年03月09日</dt>
                            <dd>新增文章搜索功能！</dd>
                            <dt>2017年02月25日</dt>
                            <dd>QQ互联接入网站，可QQ登陆发表评论与留言！</dd>
                        </dl>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">后台记录</div>
                        <dl class="footprint">
                            <dt>2017年03月16日</dt>
                            <dd>分页新增页容量控制</dd>
                            <dt>2017年03月12日</dt>
                            <dd>新增管家提醒功能</dd>
                            <dt>2017年03月10日</dt>
                            <dd>新增Win10快捷菜单</dd>
                        </dl>
                    </div>
                    <div class="blog-module shadow">
                        <div class="blog-module-title">友情链接</div>
                        <ul class="blogroll">
                            <li><a target="_blank" href="http://www.layui.com/" title="Layui">Layui</a></li>
                            <li><a target="_blank" href="http://www.pagemark.cn/" title="页签">页签</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>Copyright</span><span>&copy;</span><span>2017</span><a href="http://www.lyblogs.cn">不落阁</a><span>Design By LY</span></p>
        <p><a href="http://www.miibeian.gov.cn/" target="_blank">蜀ICP备16029915号-1</a></p>
    </footer>
    <!--侧边导航-->
    <ul class="layui-nav layui-nav-tree layui-nav-side blog-nav-left layui-hide" lay-filter="nav">
        <li class="layui-nav-item layui-this">
            <a href="home.html"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
        </li>
        <li class="layui-nav-item">
            <a href="article.html"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
        </li>
        <li class="layui-nav-item">
            <a href="resource.html"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
        </li>
        <li class="layui-nav-item">
            <a href="timeline.html"><i class="fa fa-road fa-fw"></i>&nbsp;点点滴滴</a>
        </li>
        <li class="layui-nav-item">
            <a href="about.html"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
        </li>
    </ul>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
    <!-- layui.js -->
    <script src={% static "plug/layui/layui.js" %}></script>
    <!-- 全局脚本 -->
    <script src={% static "js/global.js" %}></script>
    <!-- 本页脚本 -->
    <script src={% static "/js/home.js" %}></script>
</body>
</html>

django_test/templates/blog/resource.html
<!--
    
 @Name：不落阁整站模板源码
 @Author：Absolutely
 @Site：http://www.lyblogs.cn

 -->

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; Charset=gb2312">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>不落阁 - 资源分享</title>
    <link rel="shortcut icon" href="../images/Logo_40.png" type="image/x-icon">
    <!--Layui-->
    <link href="../plug/layui/css/layui.css" rel="stylesheet" />
    <!--font-awesome-->
    <link href="../plug/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!--全局样式表-->
    <link href="../css/global.css" rel="stylesheet" />
    <!-- 本页样式表 -->
    <link href="../css/resource.css" rel="stylesheet" />
</head>
<body>
    <!-- 导航 -->
    <nav class="blog-nav layui-header">
        <div class="blog-container">
            <!-- QQ互联登陆 -->
            <a href="javascript:;" class="blog-user">
                <i class="fa fa-qq"></i>
            </a>
            <a href="javascript:;" class="blog-user layui-hide">
                <img src="../images/Absolutely.jpg" alt="Absolutely" title="Absolutely" />
            </a>
            <!-- 不落阁 -->
            <a class="blog-logo" href="home.html">不落阁</a>
            <!-- 导航菜单 -->
            <ul class="layui-nav" lay-filter="nav">
                <li class="layui-nav-item">
                    <a href="home.html"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
                </li>
                <li class="layui-nav-item">
                    <a href="article.html"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
                </li>
                <li class="layui-nav-item layui-this">
                    <a href="resource.html"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
                </li>
                <li class="layui-nav-item">
                    <a href="timeline.html"><i class="fa fa-hourglass-half fa-fw"></i>&nbsp;点点滴滴</a>
                </li>
                <li class="layui-nav-item">
                    <a href="about.html"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
                </li>
            </ul>
            <!-- 手机和平板的导航开关 -->
            <a class="blog-navicon" href="javascript:;">
                <i class="fa fa-navicon"></i>
            </a>
        </div>
    </nav>
    <!-- 主体（一般只改变这里的内容） -->
    <div class="blog-body">
        <div class="blog-container">
            <blockquote class="layui-elem-quote sitemap layui-breadcrumb shadow">
                <a href="home.html" title="网站首页">网站首页</a>
                <a><cite>资源分享</cite></a>
            </blockquote>
            <div class="blog-main">
                <div class="blog-main">
                    <div class="child-nav shadow">
                        <span class="child-nav-btn child-nav-btn-this">全部</span>
                        <span class="child-nav-btn">源码</span>
                        <span class="child-nav-btn">工具</span>
                        <span class="child-nav-btn">电子书</span>
                    </div>
                    <div class="resource-main">
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <div class="resource shadow">
                            <div class="resource-cover">
                                <a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">
                                    <img src="../images/cover/201703051349045432.jpg" alt="时光轴" />
                                </a>
                            </div>
                            <h1 class="resource-title"><a href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank">时光轴</a></h1>
                            <p class="resource-abstract">本博客使用的时光轴的源码，手工打造！</p>
                            <div class="resource-info">
                                <span class="category"><a href="javascript:layer.msg(&#39;这里跳转到相应分类&#39;)"><i class="fa fa-tags fa-fw"></i>&nbsp;源码</a></span>
                                <span class="author"><i class="fa fa-user fa-fw"></i>Absolutely</span>
                                <div class="clear"></div>
                            </div>
                            <div class="resource-footer">
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填演示地址&#39;)" target="_blank"><i class="fa fa-eye fa-fw"></i>演示</a>
                                <a class="layui-btn layui-btn-small layui-btn-primary" href="javascript:layer.msg(&#39;这里填下载地址&#39;)" target="_blank"><i class="fa fa-download fa-fw"></i>下载</a>
                            </div>
                        </div>
                        <!-- 清除浮动 -->
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- 底部 -->
    <footer class="blog-footer">
        <p><span>Copyright</span><span>&copy;</span><span>2017</span><a href="http://www.lyblogs.cn">不落阁</a><span>Design By LY</span></p>
        <p><a href="http://www.miibeian.gov.cn/" target="_blank">蜀ICP备16029915号-1</a></p>
    </footer>
    <!--侧边导航-->
    <ul class="layui-nav layui-nav-tree layui-nav-side blog-nav-left layui-hide" lay-filter="nav">
        <li class="layui-nav-item">
            <a href="home.html"><i class="fa fa-home fa-fw"></i>&nbsp;网站首页</a>
        </li>
        <li class="layui-nav-item">
            <a href="article.html"><i class="fa fa-file-text fa-fw"></i>&nbsp;文章专栏</a>
        </li>
        <li class="layui-nav-item layui-this">
            <a href="resource.html"><i class="fa fa-tags fa-fw"></i>&nbsp;资源分享</a>
        </li>
        <li class="layui-nav-item">
            <a href="timeline.html"><i class="fa fa-road fa-fw"></i>&nbsp;点点滴滴</a>
        </li>
        <li class="layui-nav-item">
            <a href="about.html"><i class="fa fa-info fa-fw"></i>&nbsp;关于本站</a>
        </li>
    </ul>
    <!--分享窗体-->
    <div class="blog-share layui-hide">
        <div class="blog-share-body">
            <div style="width: 200px;height:100%;">
                <div class="bdsharebuttonbox">
                    <a class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                    <a class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                    <a class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                    <a class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
                </div>
            </div>
        </div>
    </div>
    <!--遮罩-->
    <div class="blog-mask animated layui-hide"></div>
    <!-- layui.js -->
    <script src="../plug/layui/layui.js"></script>
    <!-- 全局脚本 -->
    <script src="../js/global.js"></script>
</body>
</html>